version: "3.8"

services:

  mysql:
    image: mysql:5.7
    hostname: mysql
    container_name: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: slurm
      MYSQL_PASSWORD: password
    volumes:
      - var_lib_mysql:/var/lib/mysql

  slurmdbd:
    image: grid-engine-api-slurm-base
    build:
      context: ../..
      dockerfile: ./docker/slurm/Dockerfile.base
    command: [ "slurmdbd" ]
    container_name: slurmdbd
    hostname: slurmdbd
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - var_log_slurm:/mnt/grid-engine-api/logs
    expose:
      - "6819"
    depends_on:
      - mysql

  slurmctld:
    image: grid-engine-api-slurm-service
    build:
      context: ../..
      args:
        BASE_IMAGE: grid-engine-api-slurm-base
      dockerfile: ./docker/slurm/Dockerfile.service
    command: [ "slurmctld" ]
    container_name: slurmctld
    environment:
      TARGET_GRID_ENGINE: SLURM
    hostname: slurmctld
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/mnt/grid-engine-api/logs
    expose:
      - "6817"
      - "8080"
      - "5005"
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - "slurmdbd"

  worker1:
    image: grid-engine-api-slurm-base
    command: [ "slurmd" ]
    hostname: worker1
    container_name: worker1
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/mnt/grid-engine-api/logs
    expose:
      - "6818"
    depends_on:
      - "slurmctld"

  worker2:
    image: grid-engine-api-slurm-base
    command: [ "slurmd" ]
    hostname: worker2
    container_name: worker2
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/mnt/grid-engine-api/logs
    expose:
      - "6818"
    depends_on:
      - "slurmctld"


volumes:
  etc_munge:
  etc_slurm:
  slurm_jobdir:
  var_lib_mysql:
  var_log_slurm:
